<a href="https://colab.research.google.com/github/URK20CS1150/ML-projects/blob/main/Women_Cloth_Reviews_Prediction_with_Multi_Nomial_Na%C3%AFve_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Title of the project Women Cloth Reviews Prediction with Multi Nomial Naïve Bayes

step-1: Import Library

In [99]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

step-2 : import data

In [100]:
df=pd.read_csv("/content/Womens Clothing E-Commerce Reviews.csv.zip")
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [101]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [102]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Clothing ID              23486 non-null  int64 
 1   Age                      23486 non-null  int64 
 2   Title                    19676 non-null  object
 3   Review Text              22641 non-null  object
 4   Rating                   23486 non-null  int64 
 5   Recommended IND          23486 non-null  int64 
 6   Positive Feedback Count  23486 non-null  int64 
 7   Division Name            23472 non-null  object
 8   Department Name          23472 non-null  object
 9   Class Name               23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [104]:
df.shape

(23486, 10)

In [105]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

Data Preprocessing

In [106]:
df.isnull().sum()

Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [107]:
df['Review Text'].fillna('No Review',inplace=True)

In [108]:
df['Review Text'].isnull().sum()

0

In [109]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

Defining the target(y) and feature(X)

In [110]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [111]:
x=df['Review Text']

In [112]:
y=df['Rating']

In [113]:
df['Rating'].value_counts()

5    13131
4     5077
3     2871
2     1565
1      842
Name: Rating, dtype: int64

Train test split

In [114]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,random_state=2529,train_size=0.7,stratify=y)

In [115]:
X_train.shape,Y_train.shape,X_test.shape,Y_test.shape

((16440,), (16440,), (7046,), (7046,))

text conversion to tokens

In [116]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)
X_train=cv.fit_transform(X_train)
cv.get_feature_names_out()

array(['10 12', '10 bought', '10 fit', ..., 'yellow color', 'yoga pants',
       'zipper little'], dtype=object)

In [117]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [118]:
X_test=cv.fit_transform(X_test)

In [119]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 fit', ..., 'years come', 'years old',
       'yoga pants'], dtype=object)

In [120]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

Model Train

In [121]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train,Y_train)

MultinomialNB()

In [122]:
Y_pred=model.predict(X_test)

In [123]:
#model probalistic 
model.predict_proba(X_test)

array([[0.71118473, 0.02625165, 0.15465118, 0.01496876, 0.09294369],
       [0.02416867, 0.04769471, 0.35268622, 0.16185007, 0.41360034],
       [0.03582725, 0.06660584, 0.12226277, 0.21618005, 0.55912409],
       ...,
       [0.02320281, 0.08950939, 0.08962183, 0.16719203, 0.63047394],
       [0.01167675, 0.00202714, 0.08539004, 0.34347398, 0.55743209],
       [0.03959824, 0.05612822, 0.00688869, 0.1560574 , 0.74132745]])

In [124]:
#model evalution
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(Y_pred,Y_test))

[[  15   43  116  166  371]
 [  13   43   78  108  272]
 [  45   86  113  194  349]
 [  36   85  166  336  722]
 [ 144  213  388  719 2225]]


In [125]:
print(classification_report(Y_pred,Y_test))

              precision    recall  f1-score   support

           1       0.06      0.02      0.03       711
           2       0.09      0.08      0.09       514
           3       0.13      0.14      0.14       787
           4       0.22      0.25      0.23      1345
           5       0.56      0.60      0.58      3689

    accuracy                           0.39      7046
   macro avg       0.21      0.22      0.21      7046
weighted avg       0.37      0.39      0.37      7046



recatogeries rating as poor(0) and good(1)

In [126]:
df['Rating'].value_counts()

5    13131
4     5077
3     2871
2     1565
1      842
Name: Rating, dtype: int64

rerating 1,2,3 ratings as poor(0) and 4,5 rating makes good(1)

In [127]:
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}},inplace=True)

In [128]:
y=df['Rating']
x=df['Review Text']

train test split

In [129]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,random_state=2529,train_size=0.70,stratify=y)

featuer conversition is converted into tokens

In [130]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)


In [131]:
X_train=cv.fit_transform(X_train)

In [132]:
X_test=cv.fit_transform(X_test)

# applying the model

In [135]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()

In [137]:
model.fit(X_train,Y_train)

MultinomialNB()

model prediction

In [139]:
Y_pred=model.predict(X_test)
Y_pred

array([1, 1, 1, ..., 1, 1, 1])

model Evaluation

In [141]:
from sklearn.metrics import classification_report,confusion_matrix

In [142]:
print(confusion_matrix(Y_pred,Y_test))

[[ 449  989]
 [1134 4474]]


In [143]:
print(classification_report(Y_pred,Y_test))

              precision    recall  f1-score   support

           0       0.28      0.31      0.30      1438
           1       0.82      0.80      0.81      5608

    accuracy                           0.70      7046
   macro avg       0.55      0.56      0.55      7046
weighted avg       0.71      0.70      0.70      7046

